title: Flawd Wine
email: hello@flawdwine.co
description: >- # this means to ignore newlines until "baseurl:"
  Neighbourhood natural wine bar and bottle shop.
  Seasonal dishes meant to share. 
url: "https://flawd.netlify.app" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
permalink: pretty 

plugins:
  - jekyll-feed
  - jekyll-postcss

postcss:
  cache: false

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
